# Generated by Django 5.2.17 on 2026-09-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
        ("obras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontuacao", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("tempo_segundos", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_quiz",
                        to="obras.obra",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_quiz",
                        to="contas.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de quiz",
                "verbose_name_plural": "Resultados de quiz",
                "ordering": ["-criado_em"],
            },
        ),
    ]
