# Generated by Django 5.2.17 on 2026-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[
                            ("atual", "Atual (amarelo)"),
                            ("verde", "Verde claro"),
                            ("azul", "Azul claro"),
                            ("bordo", "Bordô claro"),
                        ],
                        default="atual",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do site",
                "verbose_name_plural": "Configuração do site",
            },
        ),
    ]
