# Generated by Django 5.2.17 on 2026-09-28 16:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_configuracaosite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfiguracaoSite",
        ),
    ]
