# Generated by Django 5.2.17 on 2026-09-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("autor", models.CharField(blank=True, max_length=150)),
                ("ilustrador", models.CharField(blank=True, max_length=150)),
                ("faixa_etaria", models.CharField(blank=True, max_length=50)),
                (
                    "capa",
                    models.ImageField(blank=True, null=True, upload_to="obras/capas/"),
                ),
                ("texto_breve", models.CharField(blank=True, max_length=300)),
                ("texto_completo", models.TextField(blank=True)),
                (
                    "topicos_resumo",
                    models.TextField(
                        blank=True,
                        help_text="Tópicos/resumo para uso do professor em sala de aula.",
                    ),
                ),
                (
                    "tempo_limite_segundos",
                    models.PositiveIntegerField(
                        default=600, help_text="Tempo total do quiz, em segundos."
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("publicada", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
                "ordering": ["ordem", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questoes",
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=300)),
                ("correta", models.BooleanField(default=False)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="obras.questao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
            },
        ),
    ]
