# Generated by Django 5.2.17 on 2026-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0002_grupo_equipe_editorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tradicionalismo_gaucho", "Tradicionalismo Gaúcho"),
                    ("pelos_pagos_do_rio_grande", "Pelos Pagos do Rio Grande"),
                    ("bioma", "Bioma"),
                    ("lendas_gauchas", "Lendas Gaúchas"),
                    ("curiosidades", "Curiosidades"),
                ],
                default="",
                help_text="Categoria temática da obra (solicitado pela cliente em 28/09/2026).",
                max_length=30,
            ),
        ),
    ]
