# Generated by Django 5.2.17 on 2026-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0003_obra_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="imagem_pagina",
            field=models.ImageField(
                blank=True,
                help_text="Aparece na página de detalhe da própria obra.",
                null=True,
                upload_to="obras/paginas/",
                verbose_name="Imagem da página da obra",
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="capa",
            field=models.ImageField(
                blank=True,
                help_text="Aparece no card da obra na página inicial.",
                null=True,
                upload_to="obras/capas/",
                verbose_name="Imagem do card (Home)",
            ),
        ),
    ]
