# Generated by Django 5.2.17 on 2026-09-28 20:37

import django.core.validators
import obras.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0004_obra_imagem_pagina_alter_obra_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="atividade_pdf",
            field=models.FileField(
                blank=True,
                help_text="Opcional. Um arquivo PDF de até 10 MB, disponível para download na página da obra. Convive com as perguntas cadastradas abaixo (acréscimo à Fase 6, pedido pela cliente em 28/09/2026).",
                null=True,
                upload_to="obras/atividades/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    obras.validators.validar_pdf,
                ],
                verbose_name="Atividade de apoio (PDF)",
            ),
        ),
    ]
