# Generated by Django 5.2.17 on 2026-09-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0005_obra_atividade_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaginaATurminha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_introducao",
                    models.TextField(blank=True, verbose_name="Texto de introdução"),
                ),
                (
                    "imagem_grupo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institucional/a_turminha/",
                        verbose_name="Imagem do grupo (os 4 personagens reunidos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página A Turminha",
                "verbose_name_plural": "Página A Turminha",
            },
        ),
        migrations.CreateModel(
            name="PaginaQuemSomos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "historia_texto",
                    models.TextField(
                        blank=True,
                        help_text="Um parágrafo por linha em branco, como no texto completo da obra.",
                        verbose_name="Texto — História do Clube",
                    ),
                ),
                (
                    "historia_imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institucional/quem_somos/",
                        verbose_name="Imagem — História do Clube",
                    ),
                ),
                (
                    "missao_texto",
                    models.TextField(blank=True, verbose_name="Texto — Missão"),
                ),
                (
                    "missao_imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institucional/quem_somos/",
                        verbose_name="Imagem — Missão",
                    ),
                ),
                (
                    "visao_texto",
                    models.TextField(blank=True, verbose_name="Texto — Visão"),
                ),
                (
                    "visao_imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institucional/quem_somos/",
                        verbose_name="Imagem — Visão",
                    ),
                ),
                (
                    "valores_imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institucional/quem_somos/",
                        verbose_name="Imagem — Valores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página Quem somos",
                "verbose_name_plural": "Página Quem somos",
            },
        ),
        migrations.CreateModel(
            name="PersonagemATurminha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "texto",
                    models.TextField(help_text="Um parágrafo por linha em branco."),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="institucional/a_turminha/"
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personagens",
                        to="obras.paginaaturminha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personagem",
                "verbose_name_plural": "Personagens",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="ValorQuemSomos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                (
                    "tema",
                    models.CharField(
                        help_text='Aparece entre parênteses ao lado do título (ex.: "criatividade").',
                        max_length=100,
                    ),
                ),
                ("texto", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="obras.paginaquemsomos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor",
                "verbose_name_plural": "Valores",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
