# Generated by Django 5.2.17 on 2026-10-01 18:01

import django.core.validators
import django.db.models.deletion
import obras.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obras", "0007_seed_conteudo_institucional"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="resumo_pdf",
            field=models.FileField(
                blank=True,
                help_text="Opcional. Um arquivo PDF de até 10 MB, disponível para download na página de Resumo da obra, além do texto em 'Tópicos para o professor' (acréscimo acordado em reunião de 01/10/2026).",
                null=True,
                upload_to="obras/resumos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    obras.validators.validar_pdf,
                ],
                verbose_name="Resumo para o professor (PDF)",
            ),
        ),
        migrations.CreateModel(
            name="TermoGlossario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termo", models.CharField(max_length=100)),
                ("definicao", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termos_glossario",
                        to="obras.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo do Glossário",
                "verbose_name_plural": "Glossário Gauchês",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
